### ISSUE TITLE
Not support Swift Package Manager (SPM)

### ISSUE THREAD

**Issue by cyberbarker** [havebeenfitz/AnchoredBottomSheet#2]

**Comment by havebeenfitz** [comment]
Thanks for reporting this. Unfortunately, I cannot pack this with SPM now since SPM doesn't support resources and non-SPM dependencies. Details here https://developer.apple.com/documentation/xcode/creating_a_standalone_swift_package_with_xcode

I think I can get rid of SnapKit, but some resources will still be unavailable for now.

My suggestion for you is to just manually grab this code and insert it to your project. Cheers!

**Comment by cyberbarker** [comment]
Thanks for the answer. I will take your advice

**Comment by havebeenfitz** [comment]
SPM Support is here. It's better to have image assets outside of the package. Carthage compatibility is also there now in 1.0.0
